### ISSUE TITLE
Code using io.vertx.rxjava.redis.RedisClient doesn't compile in 0.7.0

### ISSUE THREAD

**Issue by ukr15** [vert-x3/vertx-redis-client#143]
### Version

* vert.x core: 3.7.0
* vert.x redis client: 3.7.0

### Context

With switch from Vertx 3.6.3 to 3.7.0 code using  io.vertx.rxjava.redis.RedisClient in an  io.vertx.rxjava.core.AbstractVerticle  doesn't compile any more. The exception  'incompatible types: io.vertx.redis.RedisOptions cannot be converted to io.vertx.core.json.JsonObject' is thrown. 

### Do you have a reproducer?
The reproducer is the Redis example from manual, modified to a reactive verticle.
[redisClientTest.zip](https://github.com/vert-x3/vertx-redis-client/files/3068282/redisClientTest.zip)

### Steps to reproduce

1. Unpack redisClientTest.zip
2. cd to redisClient directory
3. Start redis-server on port 6380
4. java -jar target/redistest-1.0.0-fat.jar -->  Compilation failure
[ERROR] /Users/ukriegel/Workspaces/ADEPVertx/redisClientVerticle/src/main/java/io/vertx/examples/redis/RedisClientVerticle.java:[20,35] incompatible types: io.vertx.redis.RedisOptions cannot be converted to io.vertx.core.json.JsonObject
5. Change vertu-version in pom to 3.6.3
6. mvn clean install
7.  java -jar target/redistest-1.0.0-fat.jar --> success

### Extra

* The error doesn't occur for the original example based on no-reactive operations.

**Comment by vietj** [comment]
@pmlopes can you handle this issue ?

**Comment by ukr15** [comment]
Replacing RedisClient.create(vertx, new RedisOptions(json)) with RedisClient.create(vertx, json) the code compiles now with vertx 3.8.0.

 IMHO this issue could be closed.

**Comment by pmlopes** [comment]
Please verify with 4.0.0 milestone 4
